# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
    branches: [main, master]
    paths:
      - 'man/**'
      - 'pkgdown/**'
      - 'vignettes/**'

name: pkgdown-pr-preview

jobs:
  pkgdown-pr-preview:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ github.token }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: |
            connect
            website

      - name: Configure git
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Deploy pkgdown preview
        env:
          PR_NUMBER: "${{ github.event.pull_request.number }}"
        run: Rscript .github/pkgdown-pr-preview-build.R
